### ISSUE TITLE
can't intialize variable of type AVPlayerItemStatus with an rvalue of type NSinteger' (aka 'int')

### ISSUE THREAD

**Issue by ebrahimElgeded** [Bakuf/RTFramework#1]
AVPlayerItemStatus status = [[change objectForKey:NSKeyValueChangeNewKey] integerValue];

can't intialize variable of type AVPlayerItemStatus with an rvalue of type NSinteger' (aka 'int')

**Comment by Bakuf** [comment]
sorry for the delay, it's fixed now :D 
just had to cast the integer to AVPlayerItemStatus
